# Generated by Django 3.0.8 on 2020-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='lorem ipsum dolor soit amet', max_length=100),
            preserve_default=False,
        ),
    ]
