# Generated by Django 3.0.8 on 2020-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0002_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='demo@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
