# Generated by Django 3.0.8 on 2020-07-30 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0003_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
