# Generated by Django 3.0.8 on 2020-07-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0004_auto_20200730_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservice', to='kanatis_app.Service'),
        ),
    ]
