# Generated by Django 3.0.8 on 2020-07-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0005_auto_20200730_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
