# Generated by Django 3.0.8 on 2020-07-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0005_auto_20200729_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanatis_app.Team')),
            ],
        ),
    ]
