# Generated by Django 3.0.8 on 2020-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0006_teamservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamservices',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
