# Generated by Django 3.0.8 on 2020-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0006_auto_20200730_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='img',
            field=models.ImageField(default='Null', upload_to='about/'),
            preserve_default=False,
        ),
    ]
