# Generated by Django 3.0.8 on 2020-07-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0007_teamservices_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamservices',
            old_name='name',
            new_name='serv_name',
        ),
    ]
