# Generated by Django 3.0.8 on 2020-07-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0008_auto_20200729_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teamservices',
            name='service',
        ),
        migrations.AddField(
            model_name='team',
            name='teamservices_ptr',
            field=models.OneToOneField(auto_created=True, default=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kanatis_app.TeamServices'),
            preserve_default=False,
        ),
    ]
