# Generated by Django 3.0.8 on 2020-08-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0008_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='gmap_embed_address',
            field=models.CharField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3039.458890250417!2d49.839466314812356!3d40.37652106600894!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307da5a4c85e9f%3A0x8b209a8e1ed5eea9!2sAF%20Mall!5e0!3m2!1sen!2sro!4v1596272896826!5m2!1sen!2sro" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='kanatis_app.Service'),
        ),
    ]
