# Generated by Django 3.0.8 on 2020-07-29 14:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0012_auto_20200729_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
