# Generated by Django 3.0.8 on 2020-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0013_auto_20200729_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sertificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
