# Generated by Django 3.0.8 on 2020-08-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0016_auto_20200806_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ofice_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.PositiveIntegerField(choices=[(1, 'First position'), (2, 'Second position'), (3, 'Third position'), (4, 'Fourth position'), (5, 'fifth position'), (6, 'sixth position'), (7, 'seventh position'), (8, 'eight position'), (9, 'ninenth position'), (10, 'tenth position')], default=2, verbose_name='Position ordering'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
