# Generated by Django 3.0.8 on 2020-07-29 14:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0016_auto_20200729_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('office_hour', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Əlaqə',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'Haqqımızda'},
        ),
        migrations.AlterModelOptions(
            name='sertificateteam',
            options={'verbose_name_plural': 'Komanda Sertifikati'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Komanda'},
        ),
        migrations.AlterModelOptions(
            name='teamservices',
            options={'verbose_name_plural': 'Komanda Servisləri'},
        ),
        migrations.AlterModelOptions(
            name='textpages',
            options={'verbose_name_plural': 'Səhifə yazıları'},
        ),
    ]
