# Generated by Django 3.0.8 on 2020-08-06 18:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0019_auto_20200806_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gmap_embed_address_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='sertificateteam',
            name='sertificate_name_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='team',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status_ru',
        ),
        migrations.RemoveField(
            model_name='teamservices',
            name='serv_name_ru',
        ),
        migrations.RemoveField(
            model_name='textpages',
            name='team_member_ru',
        ),
        migrations.RemoveField(
            model_name='textpages',
            name='team_ru',
        ),
        migrations.AddField(
            model_name='subaboutus',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='subaboutus',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='subaboutus',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subaboutus',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
