# Generated by Django 3.0.8 on 2020-08-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0020_auto_20200806_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='subaboutus',
            options={'verbose_name_plural': 'Sub about'},
        ),
    ]
