# Generated by Django 3.0.8 on 2020-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0022_remove_subservice_fa_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Service ordering'),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc_az',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
