# Generated by Django 3.0.8 on 2020-08-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0023_auto_20200828_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Subservice order'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Service order'),
        ),
    ]
