# Generated by Django 3.0.8 on 2020-08-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0025_subaboutus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subaboutus',
            options={'ordering': ['order'], 'verbose_name_plural': 'Sub about'},
        ),
    ]
