# Generated by Django 3.0.8 on 2020-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0026_auto_20200828_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gmap_embed_address',
            field=models.TextField(max_length=1000, verbose_name='Gmap embeded iframe'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gmap_embed_address_az',
            field=models.TextField(max_length=1000, null=True, verbose_name='Gmap embeded iframe'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gmap_embed_address_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='Gmap embeded iframe'),
        ),
    ]
