# Generated by Django 3.0.8 on 2020-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0028_auto_20200828_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamservices',
            name='serv_name',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamservices',
            name='serv_name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teamservices',
            name='serv_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
