# Generated by Django 3.0.8 on 2020-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0029_auto_20200830_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(default='short content of the post', max_length=120),
            preserve_default=False,
        ),
    ]
