# Generated by Django 3.0.8 on 2020-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0030_post_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content_az',
            field=models.TextField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='short_content_en',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
