# Generated by Django 3.0.8 on 2020-08-30 07:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0031_auto_20200830_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_desc',
            field=models.TextField(default='short description of the team member', verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='short_desc_az',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='team',
            name='short_desc_en',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content_az',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
    ]
