# Generated by Django 3.0.8 on 2020-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanatis_app', '0032_auto_20200830_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertificateteam',
            options={'verbose_name': 'Komanda Sertifikatı', 'verbose_name_plural': 'Komanda Sertifikatları'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subservice',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='teams', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
    ]
